name: bloghub
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  sizer: ^2.0.15
  fl_chart: ^0.65.0
  google_fonts: ^6.1.0
  image_picker: ^1.1.2

  # Firebase - Compatible versions
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  firebase_storage: ^11.7.7   # ✅ Шинэ хувилбар
  cloud_firestore: ^4.15.8

  # Utilities
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  dio: ^5.4.0
  top_snackbar_flutter: ^3.1.0
  # motion_toast: ^2.6.7  # optionally keep this or the above, not both

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/